# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-25 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_auto_20190125_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['name'], 'verbose_name': '类别', 'verbose_name_plural': 'column'},
        ),
    ]
